spring.datasource.url=jdbc:postgresql://db.rsgosmgumwgwkqpaotju.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=WJg8AGRQJ0GxLc85
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===============================
# = HIKARI CONNECTION POOL (IMPORTANT FOR SUPABASE)
# ===============================
spring.datasource.hikari.maximum-pool-petSize=5
spring.datasource.hikari.minimum-idle=1
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml