package com.pumapunku.pet.infrastructure.repository;

import com.pumapunku.pet.infrastructure.repository.entity.PetEntity;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.UUID;

/**
 * Spring Data JPA repository for the {@link PetEntity} entity.
 *
 * <p>Provides the standard CRUD operations (save, findById, findAll,
 * deleteById, etc.) auto-generated by Spring Data JPA.
 * Having package-private visibility ensures it is only accessible from
 * {@link PetRepository}, respecting the infrastructure encapsulation principle.</p>
 */
interface PetRepositoryJPA extends JpaRepository<PetEntity, UUID>
{
}
