package com.pumapunku.pet.infrastructure.repository;

import com.pumapunku.pet.domain.UserDomain;
import com.pumapunku.pet.domain.filters.Filter;
import com.pumapunku.pet.infrastructure.mapper.UserMapper;
import com.pumapunku.pet.infrastructure.repository.entity.User;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;

import java.util.List;

/**
 * Custom implementation of the user repository.
 *
 * <p>Extends the standard Spring Data JPA functionality with dynamic queries
 * based on the domain filter model. Uses the JPA Criteria API to build
 * type-safe queries at runtime, relying on {@link FilterCriteriaConverter}
 * to translate domain filters into JPA predicates.</p>
 *
 * <p>Spring Data JPA auto-detects this class as the implementation of the
 * {@link UserCustomRepository} fragment thanks to the {@code Impl} suffix.</p>
 */
public class UserRepositoryImpl implements UserCustomRepository
{
    /**
     * JPA EntityManager injected by the persistence container.
     */
    @PersistenceContext
    private EntityManager em;

    /**
     * Domain filter to JPA predicate converter.
     * Instantiated as a class-level singleton since it is stateless.
     */
    private static final FilterCriteriaConverter converter = new FilterCriteriaConverter();

    /**
     * Finds users that meet the criteria defined in the domain filter.
     *
     * <p>Builds a typed Criteria query on the {@link User} entity,
     * applies the predicate generated by {@link FilterCriteriaConverter#toPredicate},
     * and maps the results to the {@link UserDomain} model.</p>
     *
     * @param filter domain filter defining the search criteria; must not be {@code null}.
     * @return list of {@link UserDomain} instances satisfying the filter; may be empty.
     */
    @Override
    public List<UserDomain> findByFilter(Filter filter)
    {
        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<User> query = cb.createQuery(User.class);
        Root<User> root = query.from(User.class);

        Predicate predicate = converter.toPredicate(filter, root, cb);
        query.where(predicate);

        return em.createQuery(query)
                .getResultList()
                .stream()
                .map(UserMapper.INSTANCE::toUserDomain)
                .toList();
    }
}
