package com.pumapunku.pet.infrastructure.mapper;

import com.pumapunku.pet.domain.Pet;
import com.pumapunku.pet.infrastructure.repository.entity.PetEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting between the JPA entity {@link PetEntity}
 * and the domain model {@link Pet}.
 *
 * <p>Handles the mapping of the {@code ManyToOne} relationship with
 * {@link com.pumapunku.pet.infrastructure.repository.entity.User}:
 * when converting from domain to entity, the flat {@code userId} field is assigned
 * as {@code user.id}; in the reverse direction, {@code user.id} is extracted
 * as {@code userId}.</p>
 */
@Mapper(componentModel = "spring")
public interface PetMapperInfrastructure
{
    /**
     * Singleton instance generated by MapStruct for use without injection.
     */
    PetMapperInfrastructure INSTANCE = Mappers.getMapper(PetMapperInfrastructure.class);

    /**
     * Converts a {@link Pet} domain model to the JPA entity {@link PetEntity}.
     *
     * @param pet domain model; must not be {@code null}.
     * @return JPA entity ready to be persisted.
     */
    @Mapping(source = "userId", target = "user.id")
    PetEntity toPetEntity(Pet pet);

    /**
     * Converts a JPA entity {@link PetEntity} to the domain model {@link Pet}.
     *
     * @param petEntity JPA entity retrieved from the database; must not be {@code null}.
     * @return domain model ready to be processed by the application layer.
     */
    @Mapping(source = "user.id", target = "userId")
    Pet toPet(PetEntity petEntity);

    @Mapping(target = "user", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    void updatePetEntity(Pet pet, @MappingTarget PetEntity entity);
}
