package com.pumapunku.pet.infrastructure.mapper;

import com.pumapunku.pet.domain.UserDomain;
import com.pumapunku.pet.infrastructure.repository.entity.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting between the JPA entity {@link User}
 * and the domain model {@link UserDomain}.
 *
 * <p>Allows the infrastructure layer to deliver domain objects to the application layer
 * without exposing JPA entities, respecting the dependency inversion principle.</p>
 */
@Mapper(componentModel = "spring")
public interface UserMapper
{
    /**
     * Singleton instance generated by MapStruct for use without dependency injection.
     */
    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    /**
     * Converts the JPA entity {@link User} to the domain model {@link UserDomain}.
     *
     * <p>The {@code isLocked} field of the entity is mapped to the {@code locked} field of the domain.</p>
     *
     * @param user JPA entity retrieved from the database; must not be {@code null}.
     * @return equivalent domain model.
     */
    @Mapping(source = "locked", target = "locked")
    UserDomain toUserDomain(User user);

    /**
     * Converts the domain model {@link UserDomain} to the JPA entity {@link User}.
     *
     * @param userDomain domain model; must not be {@code null}.
     * @return JPA entity ready to be persisted.
     */
    @Mapping(source = "locked", target = "locked")
    User toUser(UserDomain userDomain);
}
