jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
supabase.url=https://rsgosmgumwgwkqpaotju.supabase.co/storage/v1/object/
supabase.apikey=${SUPABASE_API_KEY}
supabase.bucket=pets
# CORS
cors.allowed-origin=http://midominio.local:5173
cors.allow-credentials=false