package com.pumapunku.pet.presentation.mapper;

import com.pumapunku.pet.domain.Pet;
import com.pumapunku.pet.presentation.request.PetRequest;
import com.pumapunku.pet.presentation.response.PetResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * Presentation layer MapStruct mapper for converting between
 * HTTP DTOs and the domain model {@link Pet}.
 *
 * <p>Converts:</p>
 * <ul>
 *   <li>{@link PetRequest} → {@link Pet} — when receiving a create/update request.</li>
 *   <li>{@link Pet} → {@link PetResponse} — when preparing the HTTP response.</li>
 * </ul>
 */
@Mapper(componentModel = "spring")
public interface PetMapper
{
    /**
     * Singleton instance generated by MapStruct for use without dependency injection.
     */
    PetMapper INSTANCE = Mappers.getMapper(PetMapper.class);

    /**
     * Converts a {@link PetRequest} to the domain model {@link Pet}.
     *
     * <p>{@code createdAt} and {@code userId} are ignored since they are assigned
     * automatically in the persistence and security layers respectively.</p>
     *
     * @param petRequest DTO received in the HTTP request; must not be {@code null}.
     * @return equivalent domain model.
     */
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "userId", ignore = true)
    Pet toPet(PetRequest petRequest);

    /**
     * Converts the domain model {@link Pet} to a {@link PetResponse}.
     *
     * <p>The {@code neutered} field of {@link Pet} is explicitly mapped to
     * {@code isNeutered} in {@link PetResponse} because the record declares the
     * parameter with that name and MapStruct does not resolve it automatically.</p>
     *
     * @param pet domain model; must not be {@code null}.
     * @return HTTP response DTO with the public data of the pet.
     */
    @Mapping(source = "neutered", target = "isNeutered")
    PetResponse toPetResponse(Pet pet);
}
